### PR TITLE
Add system test.

### PR DESCRIPTION
**Pull request by 130s**
@dirk-thomas Could you upload http://opensource-robotics.tokyo.jp/ar_track_alvar_4markers_tork_2017-01-30-15-03-19.bag to `download.ros.org`? Thank you in advance.
Once new URL becomes available I'll update this PR.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
It looks like the bag file is not using any compression. Is there are specific reason for it? If not, please use a rosbag compression to reduce the size please.

**Comment by 130s** [comment]
Thanks for pointing that out, I've never known that feature. The file with the same URL is now bz2 compressed.

**Comment by dirk-thomas** [comment]
Reducing the size by 68% :+1: The file is now available from: http://download.ros.org/data/ar_track_alvar/ar_track_alvar_4markers_tork_2017-01-30-15-03-19.bag

**Comment by 130s** [comment]
One of the tests added in this PR doesn't pass (either on cloud nor locally), because `tf` target frame is not found as I pasted the output below. Maybe [this question](http://answers.ros.org/question/254053/rosbag-play-pauses-while-it-shouldnt/) about `rosbag` is related and hope we'll find a solution soon.

```
$ catkin_test_results 
build/ar_track_alvar/test_results/ar_track_alvar/rostest-test_marker.xml: 2 tests, 2 errors, 0 failures
build/ar_track_alvar/test_results/ar_track_alvar/rosunit-marker_quarternions.xml: 1 tests, 0 errors, 1 failures
Summary: 9 tests, 2 errors, 1 failures
$ more build/ar_track_alvar/test_results/ar_track_alvar/rosunit-marker_quarternions.xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="60.167">
  <testcase classname="__main__.TestArAlvarRos" name="test_markers" time="60.1607">
    <failure type="AssertionError">0.04461061126854959 != -0.04805772245624329 within 3 places
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/n130s/tmp/cws_ar/src/ar_track_alvar/test/test_ar.py", line 85, in test_markers
    self.assertAlmostEqual(v_ret, v_expected, 3)
  File "/usr/lib/python2.7/unittest/case.py", line 563, in assertAlmostEqual
    raise self.failureException(msg)
    </failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[[ERROR] [WallTime: 1486507564.374816] [0.000000] "camera" passed to lookupTransform argument target_frame does not exist.  target=ar_marker_0
[ERROR] [WallTime: 1486507564.375052] [0.000000] "camera" passed to lookupTransform argument target_frame does not exist.  target=ar_marker_0
[ERROR] [WallTime: 1486507564.375263] [0.000000] "camera" passed to lookupTransform argument target_frame does not exist.  target=ar_marker_0
[ERROR] [WallTime: 1486507564.375384] [0.000000] "camera" passed to lookupTransform argument target_frame does not exist.  target=ar_marker_0
[ERROR] [WallTime: 1486507564.375854] [0.000000] "camera" passed to lookupTransform argument target_frame does not exist.  target=ar_marker_0
[ERROR] [WallTime: 1486507564.376022] [0.000000] "camera" passed to lookupTransform argument target_frame does not exist.  target=ar_marker_0
:
```

**Comment by 130s** [comment]
@dirk-thomas sorry to bother you again. Could you download a [new bag file](https://drive.google.com/file/d/0Bw_hbVS3wTLyM2NLUTU3RkJ5bGs/view?usp=sharing) and upload to download.ros.org? It's uncompressed but very short so the file size is only 100mb. Thank you in advance.

**Comment by dirk-thomas** [comment]
Done, see http://download.ros.org/data/ar_track_alvar/

**Comment by dirk-thomas** [comment]
If the previously uploaded bag file is obsolete (now or any time in the future) please let me know. Then I would delete them again.

**Comment by 130s** [comment]
> If the previously uploaded bag file is obsolete (now or any time in the future) please let me know. Then I would delete them again.

Yes, the [one ends with 2017-01-30-15-03-19.bag](http://download.ros.org/data/ar_track_alvar/ar_track_alvar_4markers_tork_2017-01-30-15-03-19.bag) can be deleted to save server resource. Thank you.

**Comment by 130s** [comment]
At this moment without #109, I expect some tests with less configuration  are supposed to fail (so obviously the overall result should fail as well). Looking at Travis' result, errors are happening as expected (tests whose name end with "BASIC" are given less configs and should fail).

Indigo-1 https://travis-ci.org/sniekum/ar_track_alvar/jobs/199885755#L2910
Indigo-2 https://travis-ci.org/sniekum/ar_track_alvar/jobs/199885756#L3337
Jade-1 https://travis-ci.org/sniekum/ar_track_alvar/jobs/199885757#L3334
Jade-2 https://travis-ci.org/sniekum/ar_track_alvar/jobs/199885758#L2940

Finally system test seems to be working as I wanted. Merging.

**Pull request merged**
