### PR TITLE
[test] Retry more to fix #115.

### LINKED ISSUE #115: Flaky test
The following test fails from time to time:
```
[ar_track_alvar:make] [ar_track_alvar.rosunit-marker_quarternions_WITHPARAM_CONFIGFULL/test_markers][FAILURE] 
[ar_track_alvar:make] -0.01889557576766243 != -0.02677659572186436 within 2 places                            
[ar_track_alvar:make]   File "/usr/lib/python2.7/unittest/case.py", line 331, in run                          
[ar_track_alvar:make]     testMethod()                                                                        
[ar_track_alvar:make]   File "/home/achim/workspace/src/ar_track_alvar/test/test_ar.py", line 97, in test_markers
[ar_track_alvar:make]     self.assertAlmostEqual(v_ret, v_expected, 2)                                           
[ar_track_alvar:make]   File "/usr/lib/python2.7/unittest/case.py", line 563, in assertAlmostEqual               
[ar_track_alvar:make]     raise self.failureException(msg)                                                       
[ar_track_alvar:make] --------------------------------------------------------------------------------         
```

### PR DESCRIPTION
**Pull request by 130s**
After having relaxed test in https://github.com/sniekum/ar_track_alvar/pull/113, it still fails occasionally. Same rationale as in the #113, retry is increased a bit more in this commit.

### CODE REVIEW

**Comment by 130s** [comment]
Hm, file not found error is happening, which is new to me...Hoping this is just hiccup on Travis or somewhere ustream, I'm just restarting the tests.

https://travis-ci.org/sniekum/ar_track_alvar/jobs/201238545#L3252
```
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/root/catkin_ws/src/ar_track_alvar --package=ar_track_alvar --results-filename test_marker_param_config-full.xml --results-base-dir /root/catkin_ws/build/ar_track_alvar/test_results /root/catkin_ws/src/ar_track_alvar/test/marker_param_config-full.test 
checking /root/catkin_ws/src/ar_track_alvar/test/marker_arg_config-full.test
... logging to rostest-e07b54712833-26828.log
... logging to rostest-e07b54712833-26821.log
... logging to rostest-e07b54712833-26822.log
... logging to rostest-e07b54712833-26830.log
[ROSUNIT] Outputting test results to /root/catkin_ws/build/ar_track_alvar/test_results/ar_track_alvar/rostest-test_marker_arg_config-basic.xml
[ROSUNIT] Outputting test results to /root/catkin_ws/build/ar_track_alvar/test_results/ar_track_alvar/rostest-test_marker_param_config-basic.xml
[ROSUNIT] Outputting test results to /root/catkin_ws/build/ar_track_alvar/test_results/ar_track_alvar/rostest-test_marker_param_config-full.xml
[ROSUNIT] Outputting test results to /root/catkin_ws/build/ar_track_alvar/test_results/ar_track_alvar/rostest-test_marker_arg_config-full.xml
Error opening rosout log file '/root/.ros/7c892e7e-f222-11e6-bb92-0242ac110002/rosout.log': No such file or directoryError opening rosout log file '/root/.ros/7c833d70-f222-11e6-bb92-0242ac110002/rosout.log': No such file or directoryError opening rosout log file '/root/.ros/7c8b6d7e-f222-11e6-bb92-0242ac110002/rosout.log': No such file or directoryError opening rosout log file '/root/.ros/7c8bf9f6-f222-11e6-bb92-0242ac110002/rosout.log': No such file or directory[FATAL] [1487014061.898240549]: Error opening file: /root/catkin_ws/src/ar_track_alvar/test/ar_track_alvar_4markers_tork_2017-02-08-11-21-14.bag
[FATAL] [1487014061.909038089]: Error opening file: /root/catkin_ws/src/ar_track_alvar/test/ar_track_alvar_4markers_tork_2017-02-08-11-21-14.bag
Missing package dependencies: ar_track_alvar/package.xml: rostest, rosbag (notify upstream maintainer)
[FATAL] [1487014062.165282588]: Error opening file: /root/catkin_ws/src/ar_track_alvar/test/ar_track_alvar_4markers_tork_2017-02-08-11-21-14.bag
[FATAL] [1487014062.185135385]: Error opening file: /root/catkin_ws/src/ar_track_alvar/test/ar_track_alvar_4markers_tork_2017-02-08-11-21-14.bag
...writing test results to /root/catkin_ws/build/ar_track_alvar/test_results/ar_track_alvar/roslaunch-check__root_catkin_ws_src_ar_track_alvar_test_marker_arg_config-full.test.xml
```

**Comment by 130s** [comment]
Both `prerelease test`s are passing (e.g. [for indigo](https://travis-ci.org/sniekum/ar_track_alvar/jobs/201238567)) while all 4 non-prerelease tests failed. Something platform issue.

**Comment by mathias-luedtke** [comment]
Have you tried to reproduce this with `run_ci`?

**Comment by mathias-luedtke** [comment]
From your logs (it's hard to read them if you restart the job ^^):
```
Downloading http://download.ros.org/data/ar_track_alvar/ar_track_alvar_4markers_tork_2017-02-08-11-21-14.bag to /root/catkin_ws/src/ar_track_alvar/test/ar_track_alvar_4markers_tork_2017-02-08-11-21-14.bag... failed ([Errno 30] Read-only file system: '/root/catkin_ws/src/ar_track_alvar/test/ar_track_alvar_4markers_tork_2017-02-08-11-21-14.bag')!
```

The src folder mounted read-only: https://github.com/ros-industrial/industrial_ci/blob/master/industrial_ci/src/docker.sh#L38 ;)
IMHO the build should not change the source in any way.

**Comment by mathias-luedtke** [comment]
Since your tests depend on your bagfile, you should add `REQUIRED` to `catkin_download_test_data`. This way it should at least fail with a nice error message.

**Comment by 130s** [comment]
> ```
> Downloading http://download.ros.org/data/ar_track_alvar/ar_track_alvar_4markers_tork_2017-02-08-11-21-14.bag to /root/catkin_ws/src/ar_track_alvar/test/ar_track_alvar_4markers_tork_2017-02-08-11-21-14.bag... failed ([Errno 30] Read-only file system: '/root/catkin_ws/src/ar_track_alvar/test/ar_track_alvar_4markers_tork_2017-02-08-11-21-14.bag')!
> ```
>
> The src folder mounted read-only: [ros-industrial/industrial_ci/industrial_ci/src/docker.sh#L38](https://github.com/ros-industrial/industrial_ci/blob/a71cf3a6cac4d6262d733547d714ee785aab1b44/industrial_ci/src/docker.sh#L39) ;)

Nice catch! That (and ROS prerelease test not forcing the source space as read-only) explains.

> IMHO the build should not change the source in any way.

Yeah, as you've found already, I know [we shoulnd't use source space as a download data storage](http://answers.ros.org/question/253787/accessing-data-downloaded-via-catkin_download_test_data/); Using `CMAKE_CURRENT_SOURCE_DIR` was a temporary workaround.

Now the tests have started passing again, so [the new issue](https://github.com/sniekum/ar_track_alvar/pull/116#issuecomment-279498349) is I think solved so back to the original issue.  @ipa-mdl Thanks!

**Comment by 130s** [comment]
Travis passed (again) Let's see how this goes...

**Comment by mathias-luedtke** [comment]
I have already tested this with `run_ci` ;)
The prerelease tests will fail, but the script succeeds due to https://github.com/ros-infrastructure/ros_buildfarm/issues/367

**Comment by 130s** [comment]
Ported to kinetic branch https://github.com/sniekum/ar_track_alvar/commit/722639c44c16c3dfb69a29b99609e89962de94e6

**Pull request merged**
