### PR TITLE
Remove meta pkg; ar_track_alvar is 'unary stack' so no need for the metapkg.

### PR DESCRIPTION
**Pull request by 130s**
<s>Looks like when discussion abot splitting the package into two to separate source and message packages, [the meta package was introduced](https://github.com/sniekum/ar_track_alvar/issues/27#issuecomment-46653970), with which https://github.com/sniekum/ar_track_alvar repository ended up holding only a single actual package. So meta pkg isn't necessary here.</s>

### CODE REVIEW

**Comment by 130s** [comment]
Er...my reasoning doesn't make sense. Rewritten below:

Looks like when discussion abot splitting the package into two to separate source and message packages, [the meta package was introduced](https://github.com/sniekum/ar_track_alvar/issues/27#issuecomment-46653970), with which https://github.com/sniekum/ar_track_alvar repository ended up holding 2 packages but only a single source package and another one is a meta pkg. So meta isn't necessary here.

**Comment by 130s** [comment]
You created the meta pkg @jihoonl. Do you see any issue with its removal?

**Comment by jihoonl** [comment]
Nope. since `ar_track_alvar` is already depending on msg package, it should be fine.

**Comment by 130s** [comment]
Thanks. Now merging.

**Pull request merged**
