### PR TITLE
Use Eigen::aligned_allocator to fix 32bit align

### PR DESCRIPTION
**Pull request by rethink-rlinsalata**
Attempts to fix 32bit alignment error in Eigen related code by using the Eigen::aligned_allocator in all STL Containers with Eigen.

**NOTE:** I'm not entirely sure this is a proper fix - it's more the thing that finally made it not crash at quarter to midnight... BUT, I wanted to do the PR to see what you thought.

See these resources for more information than I understand (particularly the first):
- http://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html
- (Cause 2:) http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html

2nd Note: This is not a completely informed fix ... it just seemed to finally fix the alignment error and make the program not crash on **32-bit 12.04 with groovy, catkin (no kinect)**.

### CODE REVIEW

**Comment by sniekum** [comment]
Thanks Rob, looks good.  Maybe at some point someone can try this with the Kinect version as well.

**Comment by rethink-rlinsalata** [comment]
This may have caused problems higher up when compiling the other
executables - I did a clean checkout after making the PR, and it failed to
build some other files because of some "no matching function for call to
...." errors.  I'm looking into it, but it gets a lot more complicated
higher up and I'm less sure on what I'm doing.  Sorry for breaking things...

**Comment by rethink-rlinsalata** [comment]
Okay, so I made a first pass fix - and now have a branch where a clean checkout compiles.  It's not pretty and I destroyed your line lengths, so I'll try to clean it up.  But for the sake of fixing the broken build, there is a version in my fork of the repo on the "eigen_32bit_fix_fix" branch (commit  referenced above):
- rethink-rlinsalata/ar_track_alvar@944575dc4e3b087ff48a067848f50a07c1de9bc0
- https://github.com/rethink-rlinsalata/ar_track_alvar/compare/eigen_32bit_fix_fix

I am somewhat worried that these changes may break other users code, given that the original commit broke code that required this commit.  If you think that's valid, we could keep these 32bit changes in a separate branch, and I can make a roll-back PR to undo the changes to groovy-devel...

For those two reasons - and since I really should test my code more before submitting PR's - I didn't make an actual PR yet for these fixes.  On the other hand, groovy-devel won't compile without them currently soo... maybe we should just put them in now, and then I can clean them up/test and see if anything else breaks after?  Whatever you'd prefer, Scott.

**Comment by sniekum** [comment]
Rob,

I just reverted it for now to the old version so people don't have
problems.  I don't feel like anything you changed should break anything
(aside from the compilation issues), but it would be best to test a bit
before releasing into the wild.  And I'm working on a deadline now, so it
isn't the best time for me to try and test something.  Make sure all the
different nodes compile (and run without crashing if you have a kinect to
test with) and let me know when it seems stable.  Thanks for looking into
this issue.

--Scott

**Pull request merged**
